// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Episode documents
 */
interface EpisodeDocumentData {
  /**
   * Name field in *Episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Special field in *Episode*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: episode.special
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  special: prismic.BooleanField;

  /**
   * Season Number field in *Episode*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.season_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  season_number: prismic.NumberField;

  /**
   * Episode Number field in *Episode*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.episode_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  episode_number: prismic.NumberField;

  /**
   * Image field in *Episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Series field in *Episode*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.series
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  series: prismic.ContentRelationshipField<"series">;
}

/**
 * Episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EpisodeDocumentData>,
    "episode",
    Lang
  >;

type EpisodepagetemplateDocumentDataSlicesSlice =
  | TextWithImageSlice
  | FourUpSlice
  | PageHeaderSlice
  | HeroSlice
  | VideoPlayerSlice;

/**
 * Content for EpisodePageTemplate documents
 */
interface EpisodepagetemplateDocumentData {
  /**
   * Slice Zone field in *EpisodePageTemplate*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episodepagetemplate.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EpisodepagetemplateDocumentDataSlicesSlice> /**
   * Meta Description field in *EpisodePageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: episodepagetemplate.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *EpisodePageTemplate*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episodepagetemplate.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *EpisodePageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: episodepagetemplate.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * EpisodePageTemplate document from Prismic
 *
 * - **API ID**: `episodepagetemplate`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodepagetemplateDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EpisodepagetemplateDocumentData>,
    "episodepagetemplate",
    Lang
  >;

type EventDocumentDataSlicesSlice =
  | HeroSlice
  | TextWithImageSlice
  | FourUpSlice;

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Name field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Tagline field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * CTALink field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event.ctalink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctalink: prismic.LinkField;

  /**
   * Thumbnail field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

type EventpagetemplateDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for EventPageTemplate documents
 */
interface EventpagetemplateDocumentData {
  /**
   * Slice Zone field in *EventPageTemplate*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: eventpagetemplate.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventpagetemplateDocumentDataSlicesSlice> /**
   * Meta Description field in *EventPageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: eventpagetemplate.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *EventPageTemplate*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventpagetemplate.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *EventPageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: eventpagetemplate.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * EventPageTemplate document from Prismic
 *
 * - **API ID**: `eventpagetemplate`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventpagetemplateDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventpagetemplateDocumentData>,
    "eventpagetemplate",
    Lang
  >;

/**
 * Item in *GlobalNav → SeriesList*
 */
export interface GlobalnavDocumentDataSerieslistItem {
  /**
   * series field in *GlobalNav → SeriesList*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.serieslist[].series
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  series: prismic.ContentRelationshipField<"series">;
}

type GlobalnavDocumentDataSlicesSlice = NavigationMenuSlice;

/**
 * Content for GlobalNav documents
 */
interface GlobalnavDocumentData {
  /**
   * Logo field in *GlobalNav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * LogoText field in *GlobalNav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.logotext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logotext: prismic.ImageField<never>;

  /**
   * LogoTextLink field in *GlobalNav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.logotextlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logotextlink: prismic.LinkField;

  /**
   * SeriesMenuTitle field in *GlobalNav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.seriesmenutitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seriesmenutitle: prismic.KeyTextField;

  /**
   * SeriesList field in *GlobalNav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.serieslist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  serieslist: prismic.GroupField<Simplify<GlobalnavDocumentDataSerieslistItem>>;

  /**
   * Slice Zone field in *GlobalNav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: globalnav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GlobalnavDocumentDataSlicesSlice>;
}

/**
 * GlobalNav document from Prismic
 *
 * - **API ID**: `globalnav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalnavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalnavDocumentData>,
    "globalnav",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = TextWithImageSlice | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | LandscapeCardSlice
  | PageHeaderSlice
  | UniversalCarouselSlice
  | TextWithImageSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Series → EpisodeList*
 */
export interface SeriesDocumentDataEpisodelistItem {
  /**
   * Episode field in *Series → EpisodeList*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: series.episodelist[].episode
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  episode: prismic.ContentRelationshipField<"episode">;
}

/**
 * Content for Series documents
 */
interface SeriesDocumentData {
  /**
   * Name field in *Series*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: series.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Series*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: series.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Primary CTA Text field in *Series*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: series.primary_cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_cta_text: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Series*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: series.primary_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta_link: prismic.LinkField;

  /**
   * Content field in *Series*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: series.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * EpisodeList field in *Series*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: series.episodelist[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  episodelist: prismic.GroupField<Simplify<SeriesDocumentDataEpisodelistItem>>;
}

/**
 * Series document from Prismic
 *
 * - **API ID**: `series`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SeriesDocumentData>, "series", Lang>;

type SeriespagetemplateDocumentDataSlicesSlice = GridSlice | HeroSlice;

/**
 * Content for SeriesPageTemplate documents
 */
interface SeriespagetemplateDocumentData {
  /**
   * Slice Zone field in *SeriesPageTemplate*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: seriespagetemplate.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SeriespagetemplateDocumentDataSlicesSlice> /**
   * Meta Description field in *SeriesPageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: seriespagetemplate.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *SeriesPageTemplate*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seriespagetemplate.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *SeriesPageTemplate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: seriespagetemplate.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * SeriesPageTemplate document from Prismic
 *
 * - **API ID**: `seriespagetemplate`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeriespagetemplateDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SeriespagetemplateDocumentData>,
    "seriespagetemplate",
    Lang
  >;

export type AllDocumentTypes =
  | EpisodeDocument
  | EpisodepagetemplateDocument
  | EventDocument
  | EventpagetemplateDocument
  | GlobalnavDocument
  | HomepageDocument
  | PageDocument
  | SeriesDocument
  | SeriespagetemplateDocument;

/**
 * Primary content in *FourUp → Primary*
 */
export interface FourUpSliceDefaultPrimary {
  /**
   * Title field in *FourUp → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: four_up.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *FourUp → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_up.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *FourUp → Items*
 */
export interface FourUpSliceDefaultItem {
  /**
   * Image field in *FourUp → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: four_up.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Header field in *FourUp → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: four_up.items[].header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Content field in *FourUp → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_up.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for FourUp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourUpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FourUpSliceDefaultPrimary>,
  Simplify<FourUpSliceDefaultItem>
>;

/**
 * Slice variation for *FourUp*
 */
type FourUpSliceVariation = FourUpSliceDefault;

/**
 * FourUp Shared Slice
 *
 * - **API ID**: `four_up`
 * - **Description**: FourUp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourUpSlice = prismic.SharedSlice<"four_up", FourUpSliceVariation>;

/**
 * Primary content in *Grid → Primary*
 */
export interface GridSliceDefaultPrimary {
  /**
   * Heading field in *Grid → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *Grid → Items*
 */
export interface GridSliceDefaultItem {
  /**
   * Image field in *Grid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Grid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Eyebrow field in *Grid → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.items[].eyebrow
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrow: prismic.TitleField;

  /**
   * ItemHeading field in *Grid → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.items[].itemheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itemheading: prismic.TitleField;

  /**
   * Body field in *Grid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridSliceDefaultPrimary>,
  Simplify<GridSliceDefaultItem>
>;

/**
 * programmatic variation for Grid Slice
 *
 * - **API ID**: `programmatic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceProgrammatic = prismic.SharedSliceVariation<
  "programmatic",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Grid*
 */
type GridSliceVariation = GridSliceDefault | GridSliceProgrammatic;

/**
 * Grid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<"grid", GridSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_cta_text: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_cta_link: prismic.LinkField;

  /**
   * Secondary CTA Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_cta_text: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_cta_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Programmatic variation for Hero Slice
 *
 * - **API ID**: `programmatic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceProgrammatic = prismic.SharedSliceVariation<
  "programmatic",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceProgrammatic;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LandscapeCardRow → Primary*
 */
export interface LandscapeCardSliceDefaultPrimary {
  /**
   * Heading field in *LandscapeCardRow → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *LandscapeCardRow → Items*
 */
export interface LandscapeCardSliceDefaultItem {
  /**
   * Image field in *LandscapeCardRow → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *LandscapeCardRow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *LandscapeCardRow → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for LandscapeCardRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandscapeCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandscapeCardSliceDefaultPrimary>,
  Simplify<LandscapeCardSliceDefaultItem>
>;

/**
 * Primary content in *LandscapeCardRow → Primary*
 */
export interface LandscapeCardSliceEpisodeSelectionPrimary {
  /**
   * Heading field in *LandscapeCardRow → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *LandscapeCardRow → Items*
 */
export interface LandscapeCardSliceEpisodeSelectionItem {
  /**
   * episode field in *LandscapeCardRow → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.items[].episode
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  episode: prismic.ContentRelationshipField<"episode">;
}

/**
 * Episode Selection variation for LandscapeCardRow Slice
 *
 * - **API ID**: `episodeSelection`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandscapeCardSliceEpisodeSelection = prismic.SharedSliceVariation<
  "episodeSelection",
  Simplify<LandscapeCardSliceEpisodeSelectionPrimary>,
  Simplify<LandscapeCardSliceEpisodeSelectionItem>
>;

/**
 * Primary content in *LandscapeCardRow → Primary*
 */
export interface LandscapeCardSliceEventSelectionPrimary {
  /**
   * Heading field in *LandscapeCardRow → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *LandscapeCardRow → Items*
 */
export interface LandscapeCardSliceEventSelectionItem {
  /**
   * Event field in *LandscapeCardRow → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: landscape_card.items[].event
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event: prismic.ContentRelationshipField<"event">;
}

/**
 * Event Selection variation for LandscapeCardRow Slice
 *
 * - **API ID**: `eventSelection`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandscapeCardSliceEventSelection = prismic.SharedSliceVariation<
  "eventSelection",
  Simplify<LandscapeCardSliceEventSelectionPrimary>,
  Simplify<LandscapeCardSliceEventSelectionItem>
>;

/**
 * Slice variation for *LandscapeCardRow*
 */
type LandscapeCardSliceVariation =
  | LandscapeCardSliceDefault
  | LandscapeCardSliceEpisodeSelection
  | LandscapeCardSliceEventSelection;

/**
 * LandscapeCardRow Shared Slice
 *
 * - **API ID**: `landscape_card`
 * - **Description**: LandscapeCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandscapeCardSlice = prismic.SharedSlice<
  "landscape_card",
  LandscapeCardSliceVariation
>;

/**
 * Primary content in *NavigationMenu → Primary*
 */
export interface NavigationMenuSliceDefaultPrimary {
  /**
   * ParentText field in *NavigationMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.primary.parenttext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parenttext: prismic.KeyTextField;
}

/**
 * Primary content in *NavigationMenu → Items*
 */
export interface NavigationMenuSliceDefaultItem {
  /**
   * ChildText field in *NavigationMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[].childtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  childtext: prismic.KeyTextField;

  /**
   * ChildLink field in *NavigationMenu → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[].childlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  childlink: prismic.LinkField;
}

/**
 * Default variation for NavigationMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationMenuSliceDefaultPrimary>,
  Simplify<NavigationMenuSliceDefaultItem>
>;

/**
 * Primary content in *NavigationMenu → Primary*
 */
export interface NavigationMenuSliceSingleItemPrimary {
  /**
   * ParentText field in *NavigationMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.primary.parenttext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parenttext: prismic.KeyTextField;

  /**
   * ParentLink field in *NavigationMenu → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.primary.parentlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parentlink: prismic.LinkField;
}

/**
 * Single Item variation for NavigationMenu Slice
 *
 * - **API ID**: `singleItem`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceSingleItem = prismic.SharedSliceVariation<
  "singleItem",
  Simplify<NavigationMenuSliceSingleItemPrimary>,
  never
>;

/**
 * Primary content in *NavigationMenu → Primary*
 */
export interface NavigationMenuSliceSeriesListingPrimary {
  /**
   * ParentText field in *NavigationMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.primary.parenttext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parenttext: prismic.KeyTextField;
}

/**
 * Primary content in *NavigationMenu → Items*
 */
export interface NavigationMenuSliceSeriesListingItem {
  /**
   * series field in *NavigationMenu → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[].series
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  series: prismic.ContentRelationshipField<"series">;
}

/**
 * SeriesListing variation for NavigationMenu Slice
 *
 * - **API ID**: `seriesListing`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceSeriesListing = prismic.SharedSliceVariation<
  "seriesListing",
  Simplify<NavigationMenuSliceSeriesListingPrimary>,
  Simplify<NavigationMenuSliceSeriesListingItem>
>;

/**
 * Primary content in *NavigationMenu → Primary*
 */
export interface NavigationMenuSliceEventListingPrimary {
  /**
   * ParentText field in *NavigationMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.primary.parenttext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parenttext: prismic.KeyTextField;
}

/**
 * Primary content in *NavigationMenu → Items*
 */
export interface NavigationMenuSliceEventListingItem {
  /**
   * event field in *NavigationMenu → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.items[].event
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event: prismic.ContentRelationshipField<"event">;
}

/**
 * EventListing variation for NavigationMenu Slice
 *
 * - **API ID**: `eventListing`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceEventListing = prismic.SharedSliceVariation<
  "eventListing",
  Simplify<NavigationMenuSliceEventListingPrimary>,
  Simplify<NavigationMenuSliceEventListingItem>
>;

/**
 * Slice variation for *NavigationMenu*
 */
type NavigationMenuSliceVariation =
  | NavigationMenuSliceDefault
  | NavigationMenuSliceSingleItem
  | NavigationMenuSliceSeriesListing
  | NavigationMenuSliceEventListing;

/**
 * NavigationMenu Shared Slice
 *
 * - **API ID**: `navigation_menu`
 * - **Description**: NavigationMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSlice = prismic.SharedSlice<
  "navigation_menu",
  NavigationMenuSliceVariation
>;

/**
 * Primary content in *PageHeader → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * Heading field in *PageHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *PageHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Programmatic variation for PageHeader Slice
 *
 * - **API ID**: `programmatic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceProgrammatic = prismic.SharedSliceVariation<
  "programmatic",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation =
  | PageHeaderSliceDefault
  | PageHeaderSliceProgrammatic;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Heading field in *TextWithImage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceImageLeftPrimary {
  /**
   * Heading field in *TextWithImage → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Left variation for TextWithImage Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<TextWithImageSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceImageLeft;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Primary content in *UniversalCarousel → Primary*
 */
export interface UniversalCarouselSliceDefaultPrimary {
  /**
   * Heading field in *UniversalCarousel → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *UniversalCarousel → Items*
 */
export interface UniversalCarouselSliceDefaultItem {
  /**
   * Image field in *UniversalCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * ImageLink field in *UniversalCarousel → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.items[].imagelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  imagelink: prismic.LinkField;

  /**
   * Eyebrow field in *UniversalCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.items[].eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *UniversalCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for UniversalCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UniversalCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UniversalCarouselSliceDefaultPrimary>,
  Simplify<UniversalCarouselSliceDefaultItem>
>;

/**
 * Primary content in *UniversalCarousel → Primary*
 */
export interface UniversalCarouselSliceEpisodeListPrimary {
  /**
   * Heading field in *UniversalCarousel → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *UniversalCarousel → Items*
 */
export interface UniversalCarouselSliceEpisodeListItem {
  /**
   * Episode field in *UniversalCarousel → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: universal_carousel.items[].episode
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  episode: prismic.ContentRelationshipField<"episode">;
}

/**
 * Episode List variation for UniversalCarousel Slice
 *
 * - **API ID**: `episodeList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UniversalCarouselSliceEpisodeList = prismic.SharedSliceVariation<
  "episodeList",
  Simplify<UniversalCarouselSliceEpisodeListPrimary>,
  Simplify<UniversalCarouselSliceEpisodeListItem>
>;

/**
 * Slice variation for *UniversalCarousel*
 */
type UniversalCarouselSliceVariation =
  | UniversalCarouselSliceDefault
  | UniversalCarouselSliceEpisodeList;

/**
 * UniversalCarousel Shared Slice
 *
 * - **API ID**: `universal_carousel`
 * - **Description**: UniversalCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UniversalCarouselSlice = prismic.SharedSlice<
  "universal_carousel",
  UniversalCarouselSliceVariation
>;

/**
 * Primary content in *VideoPlayer → Primary*
 */
export interface VideoPlayerSliceDefaultPrimary {
  /**
   * Thumbnail field in *VideoPlayer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Default variation for VideoPlayer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoPlayerSliceDefaultPrimary>,
  never
>;

/**
 * Programmatic variation for VideoPlayer Slice
 *
 * - **API ID**: `programmatic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSliceProgrammatic = prismic.SharedSliceVariation<
  "programmatic",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *VideoPlayer*
 */
type VideoPlayerSliceVariation =
  | VideoPlayerSliceDefault
  | VideoPlayerSliceProgrammatic;

/**
 * VideoPlayer Shared Slice
 *
 * - **API ID**: `video_player`
 * - **Description**: VideoPlayer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSlice = prismic.SharedSlice<
  "video_player",
  VideoPlayerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EpisodeDocument,
      EpisodeDocumentData,
      EpisodepagetemplateDocument,
      EpisodepagetemplateDocumentData,
      EpisodepagetemplateDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      EventpagetemplateDocument,
      EventpagetemplateDocumentData,
      EventpagetemplateDocumentDataSlicesSlice,
      GlobalnavDocument,
      GlobalnavDocumentData,
      GlobalnavDocumentDataSerieslistItem,
      GlobalnavDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SeriesDocument,
      SeriesDocumentData,
      SeriesDocumentDataEpisodelistItem,
      SeriespagetemplateDocument,
      SeriespagetemplateDocumentData,
      SeriespagetemplateDocumentDataSlicesSlice,
      AllDocumentTypes,
      FourUpSlice,
      FourUpSliceDefaultPrimary,
      FourUpSliceDefaultItem,
      FourUpSliceVariation,
      FourUpSliceDefault,
      GridSlice,
      GridSliceDefaultPrimary,
      GridSliceDefaultItem,
      GridSliceVariation,
      GridSliceDefault,
      GridSliceProgrammatic,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceProgrammatic,
      LandscapeCardSlice,
      LandscapeCardSliceDefaultPrimary,
      LandscapeCardSliceDefaultItem,
      LandscapeCardSliceEpisodeSelectionPrimary,
      LandscapeCardSliceEpisodeSelectionItem,
      LandscapeCardSliceEventSelectionPrimary,
      LandscapeCardSliceEventSelectionItem,
      LandscapeCardSliceVariation,
      LandscapeCardSliceDefault,
      LandscapeCardSliceEpisodeSelection,
      LandscapeCardSliceEventSelection,
      NavigationMenuSlice,
      NavigationMenuSliceDefaultPrimary,
      NavigationMenuSliceDefaultItem,
      NavigationMenuSliceSingleItemPrimary,
      NavigationMenuSliceSeriesListingPrimary,
      NavigationMenuSliceSeriesListingItem,
      NavigationMenuSliceEventListingPrimary,
      NavigationMenuSliceEventListingItem,
      NavigationMenuSliceVariation,
      NavigationMenuSliceDefault,
      NavigationMenuSliceSingleItem,
      NavigationMenuSliceSeriesListing,
      NavigationMenuSliceEventListing,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      PageHeaderSliceProgrammatic,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceImageLeftPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceImageLeft,
      UniversalCarouselSlice,
      UniversalCarouselSliceDefaultPrimary,
      UniversalCarouselSliceDefaultItem,
      UniversalCarouselSliceEpisodeListPrimary,
      UniversalCarouselSliceEpisodeListItem,
      UniversalCarouselSliceVariation,
      UniversalCarouselSliceDefault,
      UniversalCarouselSliceEpisodeList,
      VideoPlayerSlice,
      VideoPlayerSliceDefaultPrimary,
      VideoPlayerSliceVariation,
      VideoPlayerSliceDefault,
      VideoPlayerSliceProgrammatic,
    };
  }
}
