// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  four_up: dynamic(() => import("./FourUp")),
  grid: dynamic(() => import("./Grid")),
  hero: dynamic(() => import("./Hero")),
  landscape_card: dynamic(() => import("./LandscapeCardRow")),
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  page_header: dynamic(() => import("./PageHeader")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  universal_carousel: dynamic(() => import("./UniversalCarousel")),
  video_player: dynamic(() => import("./VideoPlayer")),
};
